version: '3.1'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeperDep
    ports:
      - "2181:2181"
  kafkaDep:
    image: wurstmeister/kafka
    container_name: kafkaDep
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "vuelos:3:1"